apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: microservices-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
